### ISSUE TITLE
Issue with using boto sdk when /etc/boto.cfg file with empty aws keys exists when using EC2 instance role

### ISSUE THREAD

**Issue by sebastiankasprzak** [xhost-cookbooks/boto#1]
boto::configure recipe with no additional attributes set creates following file:

```
root@ip-172-50-1-7:/opt# cat /etc/boto.cfg
[Credentials]
aws_access_key_id =
aws_secret_access_key =

[Boto]
debug = 0
num_retries = 10

ec2_region_name = us-east-1
ec2_region_endpoint = us-east-1.ec2.amazonaws.com

#proxy = myproxy.com
#proxy_port = 8080
#proxy_user = foo
#proxy_pass = bar
```

following issue occurs when trying to make a call utilising the ec2 role:

``` python
Python 2.7.11 (default, Jul 14 2016, 16:27:22)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> ec2 = boto3.client('ec2', region_name='eu-west-1')
>>> print ec2.describe_instances()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: Authorization header or parameters are not formatted correctly.
```

This also affects boto and ruby sdk.

Deleting /etc/boto.cfg file resolves the problem.

**Comment by flaccid** [comment]
No problem, thanks for the PR.
